# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50f12091e3f1181383c475f46484d01eb842999b5bd3c60d09d91764786938ac49a246ee655669062cbb125f36ed5741e9ca32377d5a0827c9b46ff64b77c0ee

test:
  secret_key_base: 4a16ed540dc5ae5cfef81ef80600f0f9a48efd1ffa838de5eb86709e5064d84cd55db156536c9aca68f1d1c175eb361d6ceb301c3089c3080968b4610e597fa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
